# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[plugins]

[plugins.powerlevel10k]
git = "https://github.com/romkatv/powerlevel10k"
tag = "v1.20.0"
profiles = ["zsh"]

[plugins.zsh-autocomplete]
git = "https://github.com/marlonrichert/zsh-autocomplete"
profiles = ["zsh"]

[plugins.F-Sy-H]
git = "https://github.com/z-shell/F-Sy-H"
tag = "v1.67"
profiles = ["zsh"]

[plugins.wezterm]
remote = "https://cdn.githubraw.com/wez/wezterm/178f35a/assets/shell-integration/wezterm.sh"
profiles = ["wezterm"]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
